#!/usr/bin/env python3
"""Generate deterministic qsort/bsearch comparator test cases."""
import json

cases = []

def add(cid, category, **kw):
    c = {"case_id": cid, "category": category}
    c.update(kw)
    cases.append(c)

# Valid qsort cases
add("qsort_valid_small_ints_01", "qsort_policy",
    fake_record_name="fake_array", synthetic_input=[5,2,8,1,9], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,2,5,8,9],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="qsort_policy",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("qsort_valid_reverse_ints_01", "qsort_policy",
    fake_record_name="demo_values", synthetic_input=[9,7,5,3,1], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,3,5,7,9],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="qsort_policy",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("qsort_valid_duplicates_01", "qsort_policy",
    fake_record_name="sample_duplicate_group", synthetic_input=[3,1,2,1,3], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,1,2,3,3],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="equal_elements_allowed", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="qsort_policy",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("qsort_valid_already_sorted_01", "qsort_policy",
    fake_record_name="synthetic_order", synthetic_input=[1,2,3,4,5], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,2,3,4,5],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="qsort_policy",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("qsort_valid_single_element_01", "qsort_policy",
    fake_record_name="toy_sort_case", synthetic_input=[42], element_count=1,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[42],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="qsort_policy",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("qsort_valid_zero_elements_01", "qsort_policy",
    fake_record_name="toy_sort_case", synthetic_input=[], element_count=0,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="qsort_policy",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("qsort_valid_records_by_key_01", "qsort_policy",
    fake_record_name="example_records", synthetic_input=[30,10,20], element_count=3,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[10,20,30],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="qsort_policy",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

# Equal elements / stability
add("qsort_equal_elements_order_unspecified_01", "stability_caveat",
    fake_record_name="sample_duplicate_group", synthetic_input=[5,5,5], element_count=3,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[5,5,5],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="equal_elements_allowed", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="stability_caveat",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="equal_element_order_unspecified", naive_expected_to_fail=False)

add("qsort_not_stable_marker_01", "stability_caveat",
    fake_record_name="fictional_items", synthetic_input=[2,1,2,1], element_count=4,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,1,2,2],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="equal_elements_allowed", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="stability_caveat",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="qsort_not_guaranteed_stable", naive_expected_to_fail=False)

# Comparator return convention
add("qsort_comparator_negative_zero_positive_marker_01", "comparator_contract",
    fake_record_name="demo_cmp_case", synthetic_input=[3,1,2], element_count=3,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,2,3],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="comparator_contract",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("qsort_boolean_comparator_not_enough_marker_01", "comparator_contract",
    fake_record_name="demo_cmp_case", synthetic_input=[3,1,2], element_count=3,
    element_size_label="sizeof(int)", comparator_label="boolean_comparator_invalid",
    expected_sorted=[1,2,3],
    comparator_return_convention="boolean_only",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="comparator_contract",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="boolean_return_insufficient", naive_expected_to_fail=True)

# Safe comparator patterns
add("safe_int_comparator_relational_marker_01", "comparator_contract",
    fake_record_name="demo_cmp_case", synthetic_input=[7,3,9], element_count=3,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[3,7,9],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="comparator_contract",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

add("safe_int_comparator_branchless_marker_01", "comparator_contract",
    fake_record_name="demo_cmp_case", synthetic_input=[4,2,6], element_count=3,
    element_size_label="sizeof(int)", comparator_label="safe_int_branchless",
    expected_sorted=[2,4,6],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="comparator_contract",
    expected_status="success", expected_c_harness_observation="sorted_correctly",
    expected_qsort_observation="array_sorted", expected_bsearch_observation="n/a",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False)

# Subtraction overflow footguns
add("subtraction_comparator_overflow_triplet_marker_01", "overflow_caveat",
    fake_record_name="synthetic_triplet", synthetic_input=[2147483647, -2147483648, 0], element_count=3,
    element_size_label="sizeof(int)", comparator_label="subtraction_comparator_unsafe",
    expected_sorted=[-2147483648, 0, 2147483647],
    comparator_return_convention="a_minus_b_overflow_risk",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="overflow_caveat",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="signed_overflow_risk_subtraction_is_not_comparison", naive_expected_to_fail=True)

add("subtraction_comparator_nontransitive_marker_01", "overflow_caveat",
    fake_record_name="synthetic_triplet", synthetic_input=[2147483640, -10, 10], element_count=3,
    element_size_label="sizeof(int)", comparator_label="subtraction_comparator_unsafe",
    expected_sorted=[-10, 10, 2147483640],
    comparator_return_convention="a_minus_b_overflow_risk",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="overflow_caveat",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="signed_overflow_breaks_transitivity", naive_expected_to_fail=True)

add("subtraction_comparator_not_passed_to_qsort_01", "invalid_comparator_not_run",
    fake_record_name="demo_cmp_case", synthetic_input=[100, -100, 0], element_count=3,
    element_size_label="sizeof(int)", comparator_label="subtraction_comparator_unsafe",
    expected_sorted=[-100, 0, 100],
    comparator_return_convention="a_minus_b_overflow_risk",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="invalid_comparator_not_run",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="subtraction_comparator_not_passed_to_qsort", naive_expected_to_fail=True)

# Invalid comparators – not run
add("random_comparator_not_run_01", "invalid_comparator_not_run",
    fake_record_name="toy_sort_case", synthetic_input=[1,2,3], element_count=3,
    element_size_label="sizeof(int)", comparator_label="random_comparator_invalid",
    expected_sorted=[1,2,3],
    comparator_return_convention="random",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="invalid_comparator_not_run",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="random_comparator_invalid", naive_expected_to_fail=True)

add("stateful_flipping_comparator_not_run_01", "invalid_comparator_not_run",
    fake_record_name="toy_sort_case", synthetic_input=[1,2,3], element_count=3,
    element_size_label="sizeof(int)", comparator_label="stateful_flipping_invalid",
    expected_sorted=[1,2,3],
    comparator_return_convention="stateful",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="invalid_comparator_not_run",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="stateful_comparator_invalid", naive_expected_to_fail=True)

add("cyclic_modulo_comparator_not_run_01", "invalid_comparator_not_run",
    fake_record_name="toy_sort_case", synthetic_input=[1,2,3], element_count=3,
    element_size_label="sizeof(int)", comparator_label="cyclic_modulo_invalid",
    expected_sorted=[1,2,3],
    comparator_return_convention="cyclic",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="invalid_comparator_not_run",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="cyclic_comparator_nontransitive", naive_expected_to_fail=True)

add("nan_like_partial_order_not_run_01", "invalid_comparator_not_run",
    fake_record_name="synthetic_nan_like_case", synthetic_input=[1,2,3], element_count=3,
    element_size_label="sizeof(int)", comparator_label="nan_like_partial_order_invalid",
    expected_sorted=[1,2,3],
    comparator_return_convention="partial_order",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="invalid_comparator_not_run",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="partial_order_invalid_for_qsort", naive_expected_to_fail=True)

add("inconsistent_equal_comparator_not_run_01", "invalid_comparator_not_run",
    fake_record_name="demo_cmp_case", synthetic_input=[1,2,3], element_count=3,
    element_size_label="sizeof(int)", comparator_label="inconsistent_equal_invalid",
    expected_sorted=[1,2,3],
    comparator_return_convention="inconsistent",
    total_order_expectation=False, antisymmetry_expectation=False, transitivity_expectation=False,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="qsort", context_label="invalid_comparator_not_run",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_comparator",
    expected_qsort_observation="not_run", expected_bsearch_observation="n/a",
    expected_comparator_check="fail", expected_safe_comparator="unsafe",
    expected_naive_comparator="fail",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="inconsistent_equal_invalid", naive_expected_to_fail=True)

# Comparator contract checkers
for i, (cid, cat, tot, anti, trans, check) in enumerate([
    ("comparator_total_order_checker_pass_01", "comparator_contract", True, True, True, "pass"),
    ("comparator_total_order_checker_fail_01", "comparator_contract", False, False, False, "fail"),
    ("comparator_antisymmetry_checker_pass_01", "comparator_contract", True, True, True, "pass"),
    ("comparator_antisymmetry_checker_fail_01", "comparator_contract", True, False, True, "fail"),
    ("comparator_transitivity_checker_pass_01", "comparator_contract", True, True, True, "pass"),
    ("comparator_transitivity_checker_fail_01", "comparator_contract", True, True, False, "fail"),
]):
    status = "success" if check=="pass" else "skip"
    obs = "comparator_contract_ok" if check=="pass" else "not_run_invalid_comparator"
    add(cid, cat,
        fake_record_name="demo_cmp_case", synthetic_input=[1,2,3], element_count=3,
        element_size_label="sizeof(int)",
        comparator_label="safe_int_relational" if check=="pass" else "subtraction_comparator_unsafe",
        expected_sorted=[1,2,3],
        comparator_return_convention="negative_zero_positive" if check=="pass" else "a_minus_b_overflow_risk",
        total_order_expectation=tot, antisymmetry_expectation=anti, transitivity_expectation=trans,
        duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
        operation_label="qsort", context_label="comparator_contract",
        expected_status=status, expected_c_harness_observation=obs,
        expected_qsort_observation="array_sorted" if check=="pass" else "not_run",
        expected_bsearch_observation="n/a",
        expected_comparator_check=check, expected_safe_comparator="safe" if check=="pass" else "unsafe",
        expected_naive_comparator="may_pass_small_values" if check=="pass" else "fail",
        expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
        expected_fail_reason="" if check=="pass" else "contract_violation",
        naive_expected_to_fail=(check=="fail"))

# bsearch cases
add("bsearch_found_sorted_array_marker_01", "bsearch_policy",
    fake_record_name="toy_bsearch_case", synthetic_input=[1,3,5,7,9], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,3,5,7,9],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="bsearch", context_label="bsearch_policy",
    expected_status="success", expected_c_harness_observation="bsearch_found",
    expected_qsort_observation="n/a", expected_bsearch_observation="key_found",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False,
    bsearch_key=5, bsearch_expected_found=True)

add("bsearch_missing_sorted_array_marker_01", "bsearch_policy",
    fake_record_name="toy_bsearch_case", synthetic_input=[1,3,5,7,9], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,3,5,7,9],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="bsearch", context_label="bsearch_policy",
    expected_status="success", expected_c_harness_observation="bsearch_missing",
    expected_qsort_observation="n/a", expected_bsearch_observation="key_not_found",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False,
    bsearch_key=4, bsearch_expected_found=False)

add("bsearch_requires_sorted_input_marker_01", "bsearch_policy",
    fake_record_name="toy_bsearch_case", synthetic_input=[1,3,5,7,9], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,3,5,7,9],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="bsearch", context_label="bsearch_policy",
    expected_status="success", expected_c_harness_observation="bsearch_found",
    expected_qsort_observation="n/a", expected_bsearch_observation="key_found",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="bsearch_requires_sorted_input", naive_expected_to_fail=False,
    bsearch_key=3, bsearch_expected_found=True)

add("bsearch_unsorted_input_not_run_01", "invalid_comparator_not_run",
    fake_record_name="toy_bsearch_case", synthetic_input=[5,1,9,3,7], element_count=5,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[1,3,5,7,9],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="bsearch", context_label="invalid_comparator_not_run",
    expected_status="skip", expected_c_harness_observation="not_run_invalid_input",
    expected_qsort_observation="n/a", expected_bsearch_observation="not_run",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="bsearch_unsorted_input_invalid", naive_expected_to_fail=False,
    bsearch_key=5, bsearch_expected_found=True)

add("bsearch_comparator_consistency_marker_01", "bsearch_policy",
    fake_record_name="toy_bsearch_case", synthetic_input=[2,4,6,8], element_count=4,
    element_size_label="sizeof(int)", comparator_label="safe_int_relational",
    expected_sorted=[2,4,6,8],
    comparator_return_convention="negative_zero_positive",
    total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
    duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
    operation_label="bsearch", context_label="bsearch_policy",
    expected_status="success", expected_c_harness_observation="bsearch_found",
    expected_qsort_observation="n/a", expected_bsearch_observation="key_found",
    expected_comparator_check="pass", expected_safe_comparator="safe",
    expected_naive_comparator="may_pass_small_values",
    expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
    expected_fail_reason="", naive_expected_to_fail=False,
    bsearch_key=6, bsearch_expected_found=True)

# qsort parameters / edge cases
for cid, cat, esize, count, base_ok, ctx, status, fail_reason in [
    ("qsort_size_parameter_marker_01", "qsort_policy", "sizeof(int)", 3, True, "qsort_policy", "success", ""),
    ("qsort_nmemb_size_t_marker_01", "qsort_policy", "sizeof(int)", 4, True, "qsort_policy", "success", ""),
    ("qsort_void_pointer_cast_marker_01", "qsort_policy", "sizeof(int)", 3, True, "qsort_policy", "success", ""),
    ("qsort_element_size_mismatch_not_run_01", "invalid_comparator_not_run", "mismatch", 3, True, "invalid_comparator_not_run", "skip", "element_size_mismatch"),
    ("qsort_null_base_zero_count_scope_marker_01", "qsort_policy", "sizeof(int)", 0, True, "qsort_policy", "success", ""),
    ("qsort_null_base_positive_count_not_run_01", "invalid_comparator_not_run", "sizeof(int)", 3, False, "invalid_comparator_not_run", "skip", "null_base_positive_count"),
]:
    add(cid, cat,
        fake_record_name="demo_cmp_case", synthetic_input=[2,1,3][:count] if count>0 else [],
        element_count=count, element_size_label=esize,
        comparator_label="safe_int_relational",
        expected_sorted=sorted([2,1,3][:count]),
        comparator_return_convention="negative_zero_positive",
        total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
        duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
        operation_label="qsort", context_label=ctx,
        expected_status=status,
        expected_c_harness_observation="sorted_correctly" if status=="success" else "not_run_invalid_input",
        expected_qsort_observation="array_sorted" if status=="success" else "not_run",
        expected_bsearch_observation="n/a",
        expected_comparator_check="pass", expected_safe_comparator="safe",
        expected_naive_comparator="may_pass_small_values",
        expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
        expected_fail_reason=fail_reason, naive_expected_to_fail=False)

# Portability / implementation context markers (not run)
portability_cases = [
    ("qsort_r_posix_gnu_bsd_portability_marker_01", "extension_not_required", "qsort_r portability differs: GNU vs BSD signature"),
    ("qsort_s_annex_k_context_marker_01", "extension_not_required", "qsort_s Annex K context parameter, not ISO C portable"),
    ("global_state_comparator_context_marker_01", "extension_not_required", "global state comparator context, not thread-safe"),
    ("function_pointer_overhead_context_marker_01", "implementation_context", "qsort function-pointer overhead, HN performance discussion"),
    ("std_sort_context_not_tested_01", "production_sort_not_tested", "C++ std::sort context, not tested in C lab"),
    ("rust_java_safety_context_not_tested_01", "production_sort_not_tested", "Rust/Java comparator safety, not tested"),
    ("glibc_malloc_fallback_not_reproduced_01", "implementation_context", "glibc malloc fallback OOB, not reproduced"),
    ("glibc_oob_vulnerability_not_reproduced_01", "implementation_context", "glibc OOB vulnerability, not reproduced"),
    ("cve_boundary_context_marker_01", "implementation_context", "CVE assignment boundary, HN discussion context"),
    ("dynamic_linking_patch_context_marker_01", "implementation_context", "dynamic linking patch context, glibc fix applies system-wide"),
    ("production_sort_not_tested_01", "production_sort_not_tested", "production sort library, not tested"),
    ("safety_caveat_01", "safety_scope", "toy lab safety caveats – not production sorting"),
]
for cid, cat, reason in portability_cases:
    add(cid, cat,
        fake_record_name="toy_context_case", synthetic_input=[1,2], element_count=2,
        element_size_label="sizeof(int)", comparator_label="safe_int_relational",
        expected_sorted=[1,2],
        comparator_return_convention="negative_zero_positive",
        total_order_expectation=True, antisymmetry_expectation=True, transitivity_expectation=True,
        duplicate_policy="n/a", stability_expectation="not_stable_unspecified",
        operation_label="qsort", context_label=cat,
        expected_status="not_tested", expected_c_harness_observation="not_tested",
        expected_qsort_observation="not_tested", expected_bsearch_observation="not_tested",
        expected_comparator_check="not_tested", expected_safe_comparator="not_tested",
        expected_naive_comparator="not_tested",
        expected_portability_truth="not_tested", expected_production_sort_truth="not_tested",
        expected_fail_reason=reason, naive_expected_to_fail=False)

with open("cases.json", "w") as f:
    json.dump(cases, f, indent=2)
print(f"Wrote {len(cases)} cases to cases.json")
